# Jujitsu Configuration
# Next-generation version control system configuration

[user]
name = "Mac Long"
email = "hello@maclong.uk"

[signing]
behavior = "own"
backend = "ssh"
key = "/Users/mac/.ssh/id_ed25519"

# UI preferences
[ui]
default-command = "log"
editor = "hx"

# Conditional configuration for work repositories
[[--scope]]
--when.repositories = ["~/Developer/work"]
[--scope.user]
email = "mac@work.com"
