[tools]
"aqua:docker/cli" = "28.2.2"
docker-compose = "latest"
colima = "latest"
deno = "latest"
ffmpeg = "latest"
github-cli = "latest"
helix = "latest"
lima = "latest"
node = "latest"
shellcheck = "latest"
shfmt = "latest"
