[tools]
"deno" = { version = "latest", postinstall = "deno install -gArf --name claude npm:@anthropic-ai/claude-code"}
"github-cli" = "latest"
"shellcheck" = "latest"
"shfmt" = "latest"
"helix" = "latest"
