[settings]
experimental = true

[tools]
github-cli = 'latest'
helix = 'latest'
node = 'lts'
shellcheck = 'latest'
shfmt = 'latest'
'spm:maclong9/list' = 'latest'
'npm:vscode-langservers-extracted' = 'latest'
'npm:@anthropic-ai/claude-code' = 'latest'
