[settings]
experimental = true

[tools]
github-cli = 'latest'
harper-ls = 'latest'
helix = 'latest'
marksman = 'latest'
node = 'lts'
shellcheck = 'latest'
shfmt = 'latest'
zoxide = 'latest'
'ubi:bensadeh/circumflex' = { version = 'latest', matching = 'darwin_arm64' }
'spm:maclong9/list' = 'latest'
'npm:@anthropic-ai/claude-code' = 'latest'
'npm:@tailwindcss/language-server' = 'latest'
'npm:bash-language-server' = 'latest'
'npm:typescript' = 'latest'        
'npm:typescript-language-server' = 'latest'
'npm:vscode-langservers-extracted' = 'latest'
