[tools]
"deno" = "latest"
"github-cli" = "latest"
"marksman" = "latest"
"node" = "latest"
"shellcheck" = "latest"
"shfmt" = "latest"
# npm installs
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:wrangler" = "latest"
"npm:yaml-language-server" = "latest"
