[tools]
"deno" = { version = "latest", postinstall = """
  deno install -gArf --name claude npm:@anthropic-ai/claude-code
  deno install -gArf npm:typescript-language-server
""" }
"github-cli" = "latest"
"shellcheck" = "latest"
"shfmt" = "latest"
"helix" = "latest"
