[settings]
experimental = true
[tools]
github-cli = 'latest'
helix = 'latest'
marksman = 'latest'
node = 'lts'
shellcheck = 'latest'
shfmt = 'latest'
# Swift Package Manager Packages
'spm:maclong9/list' = 'latest'
#'spm:apple/container' = 'latest'
# Global Node Modules
'npm:pnpm' = 'latest'
'npm:typescript' = 'latest'
'npm:typescript-language-server' = 'latest'
'npm:vscode-langservers-extracted' = 'latest'
'npm:wrangler' = 'latest'
'npm:yaml-language-server' = 'latest'
'npm:@anthropic-ai/claude-code' = 'latest'
'npm:@google/gemini-cli' = 'latest'
'npm:@tailwindcss/language-server' = 'latest'
