theme = "vesper"

[editor]
line-number = "relative"
cursorline = true
auto-completion = true
completion-trigger-len = 1
bufferline = "multiple"
true-color = true
shell = ["zsh", "-i", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "register", "position"] 

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[editor.indent-guides]
render = true

[keys.normal]
"S-h" = "goto_previous_buffer"
"S-l" = "goto_next_buffer"

[keys.insert]
"C-[" = "normal_mode"
