# • Theme configuration
theme = "vesper"

# • Editor settings
[editor]
auto-completion = true
bufferline = "multiple"
completion-trigger-len = 1
cursorline = true
line-number = "relative"
true-color = true

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 5000

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position"]

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "none"

# • Keybindings
[keys.insert]
"C-[" = "normal_mode"
# Line commands
"C-a" = "goto_line_start"
"C-u" = "kill_to_line_start"
"C-e" = "goto_line_end"
"C-k" = "kill_to_line_end"
"C-n" = "move_line_down"
"C-p" = "move_line_up"
# Character commands
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"C-d" = "delete_char_forward"
"C-h" = "delete_char_backward"
# Word commands
"A-f" = "move_next_word_end"
"A-b" = "move_prev_word_start"
"A-d" = "delete_word_forward"
"C-w" = "delete_word_backward"

[keys.normal]
# Window navigation
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

[keys.select]
"C-[" = "normal_mode"
