theme = "fleet_dark"

[editor]
line-number = "relative"

[editor.auto-save]
after-delay.enable = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
