[settings]
experimental = true
idiomatic_version_file_enable_tools = ["swift"]

[tools]
github-cli = 'latest'
harper-ls = 'latest'
helix = "latest"
marksman = 'latest'
node = 'lts'
pkl = "latest"
"ubi:apple/pkl" = { version = "latest", matching = "pkldoc-macos-aarch64", exe = "pkldoc" }
shellcheck = 'latest'
shfmt = 'latest'
zoxide = 'latest'
'npm:@tailwindcss/language-server' = 'latest'
'npm:bash-language-server' = 'latest'
'npm:typescript' = 'latest'        
'npm:typescript-language-server' = 'latest'
'npm:vscode-langservers-extracted' = 'latest'
"npm:wrangler" = "latest"
"spm:maclong9/list" = "v1.3.0"
