[settings]
experimental = true
idiomatic_version_file_enable_tools = ["swift"]

[tools]
bat = "latest"
github-cli = "latest"
harper-ls = "latest"
helix = "latest"
marksman = "latest"
node = "lts"
pkl = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
zoxide = "latest"
"npm:@openai/codex" = "latest"
"npm:bash-language-server" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:wrangler" = "latest"
"spm:maclong9/list" = "latest"
