[settings]
experimental = true
[tools]
deno = "latest"
fzf = "latest"
github-cli = "latest"
harper-ls = "latest"
helix = "latest"
jj = "latest"
node = "lts"
shellcheck = "latest"
shfmt = "latest"
zoxide = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:vercel" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"spm:maclong9/list" = "latest"
