# mise configuration file
# Manages development tools and runtime versions

[settings]
# Enable experimental features
experimental = true

[tools]
# Swift Package Manager tools
"spm:maclong9/list" = "latest"

# Development tools
"deno" = "latest"
"jj" = "latest"      
"helix" = "latest"   
"bat" = "latest"     
"shellcheck" = "latest"
"usage" = "latest"
"shfmt" = "latest"   
"zoxide" = "latest"

# JavaScript/TypeScript ecosystem
"node" = "lts"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@tailwindcss/language-server" = "latest"
fzf = "latest"

# Environment variables
[env]
EDITOR = "hx"
PAGER = "bat"
